<label for="<?php echo $this->getFieldId('insc_est')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Inscricao Estadual') ?></label>
<div class="input-box">
    <input type="text" id="<?php echo $this->getFieldId('insc_est')?>" name="<?php echo $this->getFieldName('insc_est')?>" value="<?php echo $this->escapeHtml($this->getInscEst()) ?>" title="<?php echo $this->__('Inscricao Estadual') ?>" class="input-text" <?php echo $this->getFieldParams() ?> />
</div>