<label for="<?php echo $this->getFieldId('nome_fantasia')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Nome Fantasia') ?></label>
<div class="input-box">
    <input type="text" id="<?php echo $this->getFieldId('nome_fantasia')?>" name="<?php echo $this->getFieldName('nome_fantasia')?>" value="<?php echo $this->escapeHtml($this->getNomeFantasia()) ?>" title="<?php echo $this->__('Nome Fantasia') ?>" class="input-text" <?php echo $this->getFieldParams() ?> />
</div>