<label for="<?php echo $this->getFieldId('rg')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('RG') ?></label>
<div class="input-box">
    <input type="text" id="<?php echo $this->getFieldId('rg')?>" name="<?php echo $this->getFieldName('rg')?>" value="<?php echo $this->escapeHtml($this->getRg()) ?>" title="<?php echo $this->__('RG') ?>" class="input-text" <?php echo $this->getFieldParams() ?> />
</div>