<label for="<?php echo $this->getFieldId('tipo_pessoa')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Tipo Pessoa') ?></label>
<div class="input-box">
    <select id="<?php echo $this->getFieldId('tipo_pessoa')?>" name="<?php echo $this->getFieldName('tipo_pessoa')?>" title="<?php echo $this->__('Tipo Pessoa') ?>"<?php if ($this->isRequired()):?> class="validate-select"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
        <?php $options = Mage::getSingleton('idecheckoutvm/customer_attribute_source_pessoa_view')->getAllOptions();?>
        <?php $value = $this->getTipoPessoa();?>
        <?php foreach ($options as $option):?>
            <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
        <?php endforeach;?>
    </select>
</div>