<?php if(!Mage::helper('idecheckoutvm/checkout')->isShowCouponLink()) {return;} ?>

<div id="idecheckoutvm-coupon-box" style="display: none;">
    <h2><?php echo $this->__('Discount Codes') ?></h2>
    <div id="idecheckoutvm-coupon-message"></div>
    <form class="coupon-bg" id="discount-coupon-form">
        <div class="discount">
            <div class="fields code">
                <label for="coupon:code" class="required"><em>*</em><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
                <input type="hidden" name="remove" id="remove:coupone" value="0" />
                <div class="input-box">
                    <input class="input-text" id="coupon:code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
                </div>
            </div>
            <div class="buttons">
                <button type="button" id="idecheckoutvm-button-coupon" class="button" title="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
                <button type="button" id="idecheckoutvm-button-cancel-coupon" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" value="<?php echo $this->__('Cancel Coupon') ?>" style="<?php echo (!strlen($this->getCouponCode()) ? 'display:none;' : '')?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
            </div>
        </div>
    </form>
    <p class="idecheckoutvm-link">
        <a href="#" id="idecheckoutvm-link-coupon-close"><?php echo $this->__('Fechar') ?></a>
    </p>
</div>

<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', function() {
        var checkoutVmCouponInst = new CheckoutVmCoupon('discount-coupon-form', {
            coupon   : '<?php echo $this->getUrl('idecheckoutvm/update/coupon', array('_secure'=>true)) ?>',
            redirect : '<?php echo $this->getUrl('idecheckoutvm/index/index', array('_secure'=>true)) ?>'
        });
        $('idecheckoutvm-button-coupon').observe('click', function() {checkoutVmCouponInst.doValid()});
        $('idecheckoutvm-button-cancel-coupon').observe('click', function() {checkoutVmCouponInst.doCancel()});
        $('idecheckoutvm-link-coupon-close').observe('click', function() {checkoutVmCouponInst.doClose()});
   });
//]]>
</script>