<?php
if ($this->getQuote()->isVirtual()) : return;
endif;
?>
<script type="text/javascript">
//<![CDATA[
  var shippingMethod = new IdeShippingMethod('ide-checkout-form', {
    updateShippingMethodUrl: '<?php echo $this->getUrl('idecheckoutvm/update/shippingMethod', array('_secure' => true)) ?>'
  });
//]]>
</script>

<div id="checkout-step-shipping-method" class="idecheckoutvm-block">
  <div class="step-title step-3">
    <span><?php echo $this->__('Passo 2'); ?></span>
    <?php echo $this->__('Envio + Pagamento') ?>
  </div>
  <div class="step-body">
    <p class="data-title"><span class="icon"></span><?php echo $this->__('Selecione a forma de envio'); ?></p>
    <div id="checkout-shipping-method-load">
      <?php echo $this->getChildHtml('available') ?>
    </div>  
  </div>

  <div id="checkout-shipping-method-additional-load">
    <?php echo $this->getChildHtml('additional') ?>
  </div>
</div>

<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
  shippingMethod.addAfterValidateFunction('validate', function() {
    var ideCheckoutvmValidationInst = new IdeCheckoutvmValidation();
    $$('input[type="radio"][name="shipping_method"]').each(function(el) {
      ideCheckoutvmValidationInst.showErrorMessage(el, "<?php echo $this->helper('checkout')->__('Please specify shipping method.') ?>");
    });
    return true;
  });
//]]>
</script>